# 16.10 糟糕的錯誤處理

譯者注：該小結關於錯誤處理的觀點，譯者並不完全贊同，關於本小結的部分想法請參考[關於16.10.2小節錯誤處理的一些見解](Discussion_about_16.10.md)


依附於[第13章](13.0.md)模式的描述和[第17.1小節](17.1.md)與[第17.2.4小節](17.2.md)的總結。

## 16.10.1 不要使用布林值：

像下面程式碼一樣，建立一個布林型變數用於測試錯誤條件是多餘的：

```go
var good bool
    // 測試一個錯誤，`good`被賦為`true`或者`false`
    if !good {
        return errors.New("things aren’t good")
    }
```

立即檢測一個錯誤：

```go
... err1 := api.Func1()
if err1 != nil { … }
```

## 16.10.2 避免錯誤檢測使程式碼變得混亂：

避免寫出這樣的程式碼：

```go
... err1 := api.Func1()
if err1 != nil {
    fmt.Println("err: " + err.Error())
    return
}
err2 := api.Func2()
if err2 != nil {
...
    return
}    
```

首先，包括在一個初始化的`if`語句中對函式的呼叫。但即使程式碼中到處都是以`if`語句的形式通知錯誤（通過列印錯誤資訊）。通過這種方式，很難分辨什麼是正常的程式邏輯，什麼是錯誤檢測或錯誤通知。還需注意的是，大部分程式碼都是致力於錯誤的檢測。通常解決此問題的好辦法是儘可能以閉包的形式封裝你的錯誤檢測，例如下面的程式碼：

```go
func httpRequestHandler(w http.ResponseWriter, req *http.Request) {
    err := func () error {
        if req.Method != "GET" {
            return errors.New("expected GET")
        }
        if input := parseInput(req); input != "command" {
            return errors.New("malformed command")
        }
        // 可以在此進行其他的錯誤檢測
    } ()

        if err != nil {
            w.WriteHeader(400)
            io.WriteString(w, err)
            return
        }
        doSomething() ...
```

這種方法可以很容易分辨出錯誤檢測、錯誤通知和正常的程式邏輯（更詳細的方式參考[第13.5小節](13.5.md)）。

**在開始閲讀[第17章](17.0.md)前，先回答下列2個問題：**

- 問題 16.1：總結你能記住的所有關於`,ok`模式的情況。

- 問題 16.2：總結你能記住的所有關於`defer`模式的情況。


## 連結

- [目錄](directory.md)
- 上一節：[閉包和協程的使用](16.9.md)
- 下一章：[Go 語言模式](17.0.md)